"""Phase 3a: topic taxonomy and formula/method IDs.

  python -m pipeline.taxonomy check     validates data/taxonomy/{quant,reasoning}.json
  python -m pipeline.taxonomy render    writes TAXONOMY.md (the proposal for review)

The library files are proposals until approved (`"status": "PROPOSED"`). IDs are `<topic-slug>.<slug>`; once an
ID is published it never changes. data/taxonomy/discovery/ keeps the first labelling pass (one LLM label per
question, mapped to these IDs). Those draft tags are not the Phase 3c tags: 3c retags with QA after approval.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS = ("quant", "reasoning")
ID_RE = re.compile(r"^[a-z0-9-]+\.[a-z0-9-]+$")
ENTRY_KEYS = {"id", "topic", "subtopic", "name", "statement", "visual", "seen", "question_count"}


def load(root: Path, section: str) -> dict:
    return json.loads((root / "data" / "taxonomy" / f"{section}.json").read_text())


def check(lib: dict) -> list[str]:
    errs = []
    slugs = {t["topic"]: t["slug"] for t in lib["topics"]}
    subtopics = {(t["topic"], s["name"]) for t in lib["topics"] for s in t["subtopics"]}
    if len(set(slugs.values())) != len(slugs):
        errs.append("duplicate topic slug")
    ids = Counter(e["id"] for e in lib["entries"])
    errs += [f"duplicate id {i}" for i, n in ids.items() if n > 1]
    for e in lib["entries"]:
        if set(e) != ENTRY_KEYS:
            errs.append(f"{e.get('id')}: fields {sorted(set(e) ^ ENTRY_KEYS)}")
            continue
        if not ID_RE.match(e["id"]):
            errs.append(f"{e['id']}: not <topic-slug>.<slug>")
        if e["topic"] not in slugs:
            errs.append(f"{e['id']}: unknown topic {e['topic']}")
        elif e["id"].split(".")[0] != slugs[e["topic"]]:
            errs.append(f"{e['id']}: prefix is not the topic slug {slugs[e['topic']]}")
        if (e["topic"], e["subtopic"]) not in subtopics:
            errs.append(f"{e['id']}: unknown subtopic {e['subtopic']}")
        if e["seen"] != (e["question_count"] > 0):
            errs.append(f"{e['id']}: seen does not match question_count")
    for t in lib["topics"]:
        if sum(s["question_count"] for s in t["subtopics"]) != t["question_count"]:
            errs.append(f"{t['topic']}: subtopic counts do not add up")
    return errs


def check_tags(root: Path, section: str, lib: dict) -> list[str]:
    ids = {e["id"] for e in lib["entries"]}
    subtopics = {(t["topic"], s["name"]) for t in lib["topics"] for s in t["subtopics"]}
    path = root / "data" / "taxonomy" / "discovery" / f"{section}_draft_tags.jsonl"
    errs = []
    for tag in map(json.loads, path.read_text().splitlines()):
        if (tag["topic"], tag["subtopic"]) not in subtopics:
            errs.append(f"{tag['key']}: unknown subtopic {tag['topic']} / {tag['subtopic']}")
        errs += [f"{tag['key']}: unknown id {i}" for i in tag["formula_ids"] if i not in ids]
        if not tag["formula_ids"]:
            errs.append(f"{tag['key']}: no formula or method")
    return errs


def render(root: Path) -> str:
    libs = {s: load(root, s) for s in SECTIONS}
    lines = ["# Topic taxonomy and formula/method IDs (proposal)", "",
             "Generated by `python -m pipeline.taxonomy render` from `data/taxonomy/*.json`. "
             "Question counts come from a first labelling pass over all 1,500 questions "
             "(`data/taxonomy/discovery/`); Phase 3c retags them with a sample check.", ""]
    for s, lib in libs.items():
        es = lib["entries"]
        lines.append(f"- {s.title()}: {len(lib['topics'])} topics, "
                     f"{sum(len(t['subtopics']) for t in lib['topics'])} subtopics, {len(es)} entries "
                     f"({sum(e['seen'] for e in es)} used in the papers, {sum(not e['seen'] for e in es)} not yet seen; "
                     f"{sum(e['visual'] for e in es)} get a diagram)")
    for s, lib in libs.items():
        lines += ["", f"## {s.title()}", "", "| Topic | Slug | Questions | Subtopics |", "|---|---|---|---|"]
        for t in lib["topics"]:
            subs = "; ".join(f"{x['name']} ({x['question_count']})" for x in t["subtopics"])
            lines.append(f"| {t['topic']} | `{t['slug']}` | {t['question_count']} | {subs} |")
        for t in lib["topics"]:
            lines += ["", f"### {t['topic']}", "", "| ID | Name | Statement | Qs | Diagram |", "|---|---|---|---|---|"]
            for e in (e for e in lib["entries"] if e["topic"] == t["topic"]):
                stmt = e["statement"].replace("|", "\\|")
                lines.append(f"| `{e['id']}` | {e['name']} | {stmt} | {e['question_count'] or 'not yet seen'} "
                             f"| {'yes' if e['visual'] else ''} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["check", "render"])
    ap.add_argument("--repo-root", type=Path, default=ROOT)
    args = ap.parse_args()
    if args.command == "render":
        (args.repo_root / "TAXONOMY.md").write_text(render(args.repo_root))
        return
    errs = []
    for s in SECTIONS:
        lib = load(args.repo_root, s)
        errs += [f"{s}: {e}" for e in check(lib) + check_tags(args.repo_root, s, lib)]
    print("\n".join(errs) or "ok")
    raise SystemExit(1 if errs else 0)


if __name__ == "__main__":
    main()
