"""papers mocks questions verification

Revision ID: 0001
Revises: 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_pattern',
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('questions', sa.Integer(), nullable=False),
    sa.Column('marks_correct', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('marks_wrong', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('default_timer_sec', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('section')
    )
    op.create_table('papers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=4), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('key_status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('mocks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('timer_sec', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("section IN ('QUANT', 'REASONING')", name='mock_section'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'section')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_id', sa.String(length=48), nullable=False),
    sa.Column('q_no', sa.Integer(), nullable=False),
    sa.Column('ssc_question_id', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mock_id'], ['mocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_id', 'q_no')
    )
    op.create_index(op.f('ix_questions_ssc_question_id'), 'questions', ['ssc_question_id'], unique=False)
    op.create_table('question_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=16), nullable=False),
    sa.Column('stem_text', sa.Text(), nullable=False),
    sa.Column('stem_text_complete', sa.Boolean(), nullable=False),
    sa.Column('stem_image', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('option_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('official_answer', sa.String(length=1), nullable=True),
    sa.Column('answer_text_layer', sa.String(length=1), nullable=True),
    sa.Column('answer_page_image', sa.String(length=1), nullable=True),
    sa.Column('key_status', sa.String(length=24), nullable=False),
    sa.Column('has_visual', sa.Boolean(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('question_crop', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('subtopic', sa.Text(), nullable=True),
    sa.Column('topic_source', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'content_hash', 'official_answer'),
    sa.UniqueConstraint('question_id', 'version')
    )
    # questions <-> question_versions reference each other, so this key is added after both tables exist.
    op.create_foreign_key('fk_questions_current_version', 'questions', 'question_versions',
                          ['current_version_id'], ['id'])
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('q_no', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'section', 'q_no', 'source')
    )
    op.create_table('answer_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.Integer(), nullable=False),
    sa.Column('solver_id', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('solver_answer', sa.String(length=1), nullable=True),
    sa.Column('matches_key', sa.Boolean(), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('check_code', sa.Text(), nullable=True),
    sa.Column('check_passed', sa.Boolean(), nullable=True),
    sa.Column('check_note', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_version_id', 'solver_id', 'prompt_version')
    )
    op.create_table('question_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('shows_answer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_version_id', 'kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_assets')
    op.drop_table('answer_verifications')
    op.drop_table('review_queue')
    op.drop_constraint('fk_questions_current_version', 'questions', type_='foreignkey')
    op.drop_table('question_versions')
    op.drop_index(op.f('ix_questions_ssc_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('mocks')
    op.drop_table('papers')
    op.drop_table('exam_pattern')
    # ### end Alembic commands ###
