"""formulas and question tags

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 00:15:18.400965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('topic_slug', sa.String(length=48), nullable=False),
    sa.Column('subtopic', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('shortcut', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('entry', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulas_topic_slug'), 'formulas', ['topic_slug'], unique=False)
    op.create_table('question_formulas',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'formula_id')
    )
    op.create_index(op.f('ix_question_formulas_formula_id'), 'question_formulas', ['formula_id'], unique=False)
    op.create_table('question_tags',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('subtopic', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Text(), nullable=False),
    sa.Column('shortcut_used', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('expected_time_sec', sa.Integer(), nullable=False),
    sa.Column('has_visual', sa.Boolean(), nullable=False),
    sa.Column('tagger', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_tags_topic'), 'question_tags', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_tags_topic'), table_name='question_tags')
    op.drop_table('question_tags')
    op.drop_index(op.f('ix_question_formulas_formula_id'), table_name='question_formulas')
    op.drop_table('question_formulas')
    op.drop_index(op.f('ix_formulas_topic_slug'), table_name='formulas')
    op.drop_table('formulas')
    # ### end Alembic commands ###
