"""HTTP API over the question bank.

Run: uvicorn api.main:app --reload

Test-taker routes never return an answer key and only serve PUBLISHED mocks. /admin routes show keys, solver
runs and the review queue.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastapi import Depends, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, ConfigDict
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from api.config import settings
from api.db import get_session
from api.models import ExamPattern, Mock, Paper, Question, QuestionVersion, ReviewItem

ASSET_PREFIX = "data/questions/assets/"

app = FastAPI(title="SSC CGL Tier-1 practice API")
app.add_middleware(CORSMiddleware, allow_origins=settings.cors_origins, allow_methods=["GET"], allow_headers=["*"])
# Crops are regenerated by pipeline.extract and not committed; missing files return 404.
app.mount("/assets", StaticFiles(directory=settings.data_dir / "questions" / "assets", check_dir=False),
          name="assets")

DB = Annotated[Session, Depends(get_session)]


def asset_url(path: str | None) -> str | None:
    return "/assets/" + path.removeprefix(ASSET_PREFIX) if path else None


class Out(BaseModel):
    model_config = ConfigDict(from_attributes=True)


class PatternOut(Out):
    section: str
    questions: int
    marks_correct: float
    marks_wrong: float
    default_timer_sec: int


class MockOut(Out):
    id: str
    paper_id: str
    section: str
    timer_sec: int
    status: str


class PaperOut(Out):
    id: str
    exam_date: Any
    time_slot: str
    key_status: str
    mocks: list[MockOut]


class OptionOut(BaseModel):
    label: str
    text: str
    image_url: str | None


class QuestionOut(BaseModel):
    """What a test-taker sees: no key, and only crops that don't show the answer mark."""

    id: int
    version_id: int
    q_no: int
    stem_text: str
    stem_text_complete: bool
    stem_image_url: str | None
    options: list[OptionOut]
    has_visual: bool


class VerificationOut(Out):
    solver_id: str
    model: str | None
    prompt_version: str
    method: str | None
    solver_answer: str | None
    matches_key: bool | None
    check_passed: bool | None
    confidence: float | None
    steps: list[str]
    check_code: str | None


class AdminQuestionOut(QuestionOut):
    ssc_question_id: str | None
    status: str
    version: int
    official_answer: str | None
    answer_text_layer: str | None
    answer_page_image: str | None
    key_status: str
    review_crop_url: str | None
    source_page: int | None
    topic: str | None
    subtopic: str | None
    verifications: list[VerificationOut]


class ReviewOut(Out):
    id: int
    question_id: int | None
    paper_id: str
    section: str
    q_no: int
    source: str
    reasons: list[str]
    status: str


def question_out(q: Question) -> QuestionOut:
    v = q.current_version
    return QuestionOut(
        id=q.id, version_id=v.id, q_no=q.q_no, stem_text=v.stem_text, stem_text_complete=v.stem_text_complete,
        stem_image_url=asset_url(v.stem_image), has_visual=v.has_visual,
        options=[OptionOut(label=o["label"], text=o["text"], image_url=asset_url(o["image"])) for o in v.options])


def admin_question_out(q: Question) -> AdminQuestionOut:
    v: QuestionVersion = q.current_version
    return AdminQuestionOut(
        **question_out(q).model_dump(), ssc_question_id=q.ssc_question_id, status=q.status, version=v.version,
        official_answer=v.official_answer, answer_text_layer=v.answer_text_layer,
        answer_page_image=v.answer_page_image, key_status=v.key_status, review_crop_url=asset_url(v.question_crop),
        source_page=v.source_page, topic=v.topic, subtopic=v.subtopic,
        verifications=[VerificationOut.model_validate(x) for x in v.verifications])


def get_mock(db: Session, mock_id: str) -> Mock:
    mock = db.get(Mock, mock_id)
    if mock is None:
        raise HTTPException(404, "No such mock")
    return mock


@app.get("/health")
def health(db: DB) -> dict[str, Any]:
    return {"ok": True, "questions": db.scalar(select(func.count(Question.id)))}


@app.get("/exam-pattern", response_model=list[PatternOut])
def exam_pattern(db: DB):
    return db.scalars(select(ExamPattern).order_by(ExamPattern.section)).all()


@app.get("/papers", response_model=list[PaperOut])
def papers(db: DB):
    return db.scalars(select(Paper).order_by(Paper.id)).all()


@app.get("/mocks", response_model=list[MockOut])
def mocks(db: DB, section: str | None = None, status: str | None = None):
    query = select(Mock).order_by(Mock.id)
    if section:
        query = query.where(Mock.section == section.upper())
    if status:
        query = query.where(Mock.status == status.upper())
    return db.scalars(query).all()


@app.get("/mocks/{mock_id}/questions", response_model=list[QuestionOut])
def mock_questions(mock_id: str, db: DB):
    mock = get_mock(db, mock_id)
    if mock.status != "PUBLISHED":
        raise HTTPException(409, "This mock is not published yet: some answers are still unverified")
    return [question_out(q) for q in mock.questions]


@app.get("/admin/mocks/{mock_id}/questions", response_model=list[AdminQuestionOut])
def admin_mock_questions(mock_id: str, db: DB):
    return [admin_question_out(q) for q in get_mock(db, mock_id).questions]


@app.get("/admin/questions/{question_id}", response_model=AdminQuestionOut)
def admin_question(question_id: int, db: DB):
    q = db.get(Question, question_id)
    if q is None:
        raise HTTPException(404, "No such question")
    return admin_question_out(q)


@app.get("/admin/review-queue", response_model=list[ReviewOut])
def review_queue(db: DB, status: str = "OPEN"):
    query = select(ReviewItem).where(ReviewItem.status == status.upper())
    return db.scalars(query.order_by(ReviewItem.paper_id, ReviewItem.section, ReviewItem.q_no)).all()
